---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edc-controlplane.fullname" . }}
  labels:
    {{- include "edc-controlplane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "edc-controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/env-config: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "edc-controlplane.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edc-controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.edc.endpoints.api.port }}
              protocol: TCP
            - name: validation
              containerPort: {{ .Values.edc.endpoints.validation.port }}
              protocol: TCP
            - name: jdb
              containerPort: {{ .Values.edc.endpoints.jdb.port }}
              protocol: TCP
          env:
            - name: EDC_VAULT
              value: /connector-config/vault.properties
            - name: EDC_KEYSTORE
              value: /connector-config/cert.pfx
            - name: EDC_KEYSTORE_PASSWORD
              value: "123456"
            - name: EDC_FS_CONFIG
              value: /connector-config/configuration.properties
          volumeMounts:
            - name: consumer-control-plane-config
              mountPath: /connector-config
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/liveness
              port: default
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/readiness
              port: default
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.edc.endpoints.default.path }}/check/startup
              port: default
            failureThreshold: 12
            initialDelaySeconds: 10
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "edc-controlplane.fullname" . }}-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: consumer-control-plane-config
          configMap:
            name: consumer-control-plane-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
