auth:
  postgresPassword: <path:traceability-irs/data/dev/controlplane#databasepassword>
  username: <path:traceability-irs/data/dev/controlplane#databaseuser>
  password: <path:traceability-irs/data/dev/controlplane#databasepassword>
  database: "edc"

primary:
  resources:
    limits:
      cpu: 1.5
      memory: 1.5Gi
