{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
  password: {{ .Values.password | b64enc | quote }}
  oauthClientId: {{ .Values.oauthClientId | b64enc | quote }}
  oauthClientSecret: {{ .Values.oauthClientSecret | b64enc | quote }}
{{- end }}
