{{- if .Values.global.enablePrometheus -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  prometheus.yml: |-
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}