apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aaswrapper.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  configuration.properties: |-
    {{- .Values.configuration.properties | nindent 4 }}
  