apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aaswrapper.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aaswrapper.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_8=AASWrapper does not provide Liveness Probe
    checkov.io/skip2: CKV_K8S_9=AASWrapper does not provide Readiness Probe
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aaswrapper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aaswrapper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aaswrapper.serviceAccountName" . }}
      # @url: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 9191 # API
              protocol: TCP
            - name: callback
              containerPort: 9192 # API
              protocol: TCP  
            - name: jdb
              containerPort: 8090 # JDB
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          volumeMounts:
            - name: aaswrapper-config
              mountPath: /connector-config
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: aaswrapper-config
          configMap:
            name: {{ include "aaswrapper.fullname" . }}-config
            items:
              - key: configuration.properties
                path: configuration.properties
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
