apiVersion: v1
kind: Service
metadata:
  name: {{ include "aaswrapper.fullname" . }}
  labels:
    {{- include "aaswrapper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "aaswrapper.selectorLabels" . | nindent 4 }}
