apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omejdn-server.fullname" . }}
  labels:
    {{- include "omejdn-server.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
    {{ $key }}: "{{ $val }}"
  {{- end}}
  omejdn.yml: |-
    ---
    # A base path
    path_prefix: ''
    # Which address to bind to
    bind_to: 0.0.0.0
    # Allow Origin Header field
    allow_origin: "*"
    host: https://{{ .Values.ingress.host }}{{ .Values.ingress.rootPath }}
    openid: true
    token:
      expiration: 3600
      signing_key: {{ .Values.omejdn.serverKeyFolderPath }}/key.pem
      algorithm: RS256
      audience: "idsc:IDS_CONNECTORS_ALL"
      issuer: https://{{ .Values.ingress.host }}{{ .Values.ingress.rootPath }}
    id_token:
      expiration: 360000
      signing_key: {{ .Values.omejdn.serverKeyFolderPath }}/key.pem
      algorithm: RS256
      issuer: https://{{ .Values.ingress.host }}{{ .Values.ingress.rootPath }}
    user_backend:
    - yaml
    # Default user backend
    user_backend_default: yaml

    # User Selfservice API
    user_selfservice:
      enabled: true
      allow_deletion: true
      allow_password_change: true
      editable_attributes:
        - name
        - family_name
        - given_name
        - middle_name
        - nickname
        - preferred_username
        - profile
        - picture
        - website
        - gender
        - birthdate
        - zoneinfo
        - locale
        - updated_at
        - email
        - email_verified
        - address
        - phone_number
        - phone_number_verified

      
  
  {{- if .Values.omejdn.createDefaultAdmin }}
  clients.yml: |-
    ---
    - client_id: admin
      name: omejdn admin client
      attributes:
        - key: omejdn
          value: admin
      client_secret: admin
      token_endpoint_auth_method: client_secret_post
      scope:
        - omejdn:admin
      grant_types:
        - client_credentials
  {{- end }}


#  plugins.yml: |-
#    ---
#    - plugins:
#        admin_api:
#        token_user_attributes:
#          skip_access_token: false
#          skip_id_token: false
#
#  scope_mapping.yml: |-
#    ---
#    idsc:IDS_CONNECTOR_ATTRIBUTES_ALL:
#    - "@type"
#    - "@context"
#    - "securityProfile"
#    - "referringConnector"
