apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "omejdn-server.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
