---
# Default values for edc-dataplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the charts name
nameOverride: "irs-consumer-dataplane"
# -- Overrides the releases full name
fullnameOverride: "irs-consumer-dataplane"

## Ingress declaration to expose the network service.
ingresses:
  ## Public / Internet facing Ingress
  - enabled: true
    # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
    hostname: "irs-consumer-dataplane.dev.demo.catena-x.net"
    # -- Additional ingress annotations to add
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # -- EDC endpoints exposed by this ingress resource
    endpoints:
      - public
    # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
    className: "nginx"
    # -- Enables TLS on the ingress resource
    tls:
      - hosts:
          - "irs-consumer-dataplane.dev.demo.catena-x.net"
        # Default secret for certificate creation already provided to your namespace
        secretName: tls-secret
    ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
    certManager:
      # -- If preset enables certificate generation via cert-manager namespace scoped issuer
      issuer: ""
      # -- If preset enables certificate generation via cert-manager cluster-wide issuer
      clusterIssuer: ""

configuration:
  # -- EDC configuration.properties configuring aspects of the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector)
  properties: |-
    edc.api.auth.key=123456
    
    edc.controlplane.validation-endpoint=http://irs-consumer-controlplane:8182/validation/token
    
    edc.receiver.http.endpoint=http://aaswrapper:9192/callback
    
    edc.oauth.client.id=BC:46:85:7E:E1:1E:15:06:1F:89:7A:C6:53:88:C6:60:1C:6A:7C:8F:keyid:BC:46:85:7E:E1:1E:15:06:1F:89:7A:C6:53:88:C6:60:1C:6A:7C:8F
    edc.oauth.private.key.alias=irs-dev-daps-key-consumer
    edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
    edc.oauth.provider.jwks.url=https://daps-irs.dev.demo.catena-x.net/.well-known/jwks.json
    edc.oauth.public.key.alias=irs-dev-daps-cert-provider
    edc.oauth.token.url=https://daps-irs.dev.demo.catena-x.net/token
    
    edc.vault.hashicorp.url=https://vault.demo.catena-x.net
    edc.vault.hashicorp.token=<path:traceability-irs/data/dev/controlplane#vaultToken>
    edc.vault.hashicorp.timeout.seconds=30
    edc.vault.hashicorp.health.check.enabled=true
    edc.vault.hashicorp.health.check.standby.ok=true
    edc.vault.hashicorp.api.secret.path=/v1/traceability-irs
    
    # edc.vault.clientid=c1778e7d-db16-4404-9080-26d2280d2f63
    # edc.vault.clientsecret=<path:traceability-irs/data/dev/controlplane#devVaultClientSecret>
    # edc.vault.name=cxtsi-dev001-vault
    # edc.vault.tenantid=495463c3-0991-4659-9cc5-94b4a3f7b1d6
