---
# Default values for edc-dataplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Ingress declaration to expose the network service.
ingresses:
  ## Public / Internet facing Ingress
  - enabled: true
    # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
    hostname: "irs-provider-dataplane.dev.demo.catena-x.net"
    # -- Additional ingress annotations to add
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # -- EDC endpoints exposed by this ingress resource
    endpoints:
      - public
    # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
    className: "nginx"
    # -- Enables TLS on the ingress resource
    tls:
      - hosts:
          - "irs-provider-dataplane.dev.demo.catena-x.net"
        # Default secret for certificate creation already provided to your namespace
        secretName: tls-secret
    ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
    certManager:
      # -- If preset enables certificate generation via cert-manager namespace scoped issuer
      issuer: ""
      # -- If preset enables certificate generation via cert-manager cluster-wide issuer
      clusterIssuer: ""

configuration:
  # -- EDC configuration.properties configuring aspects of the [eclipse-dataspaceconnector](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector)
  properties: |-
    edc.api.auth.key=123456
    
    edc.controlplane.validation-endpoint=http://irs-provider-controlplane:8182/validation/token
    
    edc.oauth.client.id=AE:CF:95:1A:7F:30:7F:2C:97:EF:6F:1E:4B:C6:A7:09:CA:86:B4:D2:keyid:AE:CF:95:1A:7F:30:7F:2C:97:EF:6F:1E:4B:C6:A7:09:CA:86:B4:D2
    edc.oauth.private.key.alias=irs-dev-daps-key-provider
    edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
    edc.oauth.provider.jwks.url=https://daps-irs.dev.demo.catena-x.net/.well-known/jwks.json
    edc.oauth.public.key.alias=irs-dev-daps-cert-provider
    edc.oauth.token.url=https://daps-irs.dev.demo.catena-x.net/token
    
    edc.vault.hashicorp.url=https://vault.demo.catena-x.net/
    edc.vault.hashicorp.token=<path:traceability-irs/data/dev/controlplane#vaultToken>
    edc.vault.hashicorp.timeout.seconds=30
    edc.vault.hashicorp.health.check.standby.ok=true
    # edc.vault.hashicorp.api.secret.path=
    
    # edc.vault.clientid=c1778e7d-db16-4404-9080-26d2280d2f63
    # edc.vault.clientsecret=<path:traceability-irs/data/dev/controlplane#devVaultClientSecret>
    # edc.vault.name=cxtsi-dev001-vault
    # edc.vault.tenantid=495463c3-0991-4659-9cc5-94b4a3f7b1d6
