apiVersion: v1
kind: Service
metadata:
  name: {{ include "aasregistry.fullname" . }}
  labels:
    {{- include "aasregistry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "aasregistry.selectorLabels" . | nindent 4 }}
