# INT values for aas wrapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configuration:
  properties: |-
    web.http.port=9191
    web.http.path=/api
    web.http.callback.port=9192
    web.http.callback.path=/callback
    # wrapper.auth.basic.someuser=somepassword
    wrapper.consumer.edc.datamanagement.url=http://edc-consumer-controlplane:8181/data
    wrapper.consumer.edc.control.url=http://edc-consumer-controlplane:9999/api/controlplane/control
    wrapper.consumer.edc.apikey.name=X-Api-Key
    wrapper.consumer.edc.apikey.value=123456