apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "omejdn-server.fullname" . }}
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "200m"
        memory: "200mi"
      default:
        cpu: "400m"
        memory: "400mi"
