image:
  tag: "$ARGOCD_APP_REVISION"

ingress:
  hosts:
    - host: "irs.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "irs.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret