springprofile: dev

image:
  tag: $ARGOCD_APP_REVISION

keycloak:
  oauth2:
    clientId: <path:traceability-irs/data/dev/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-irs/data/dev/keycloak/oauth2#clientSecret>
    clientTokenUri: <path:traceability-irs/data/dev/keycloak/oauth2#tokenUri>
    jwkSetUri: <path:traceability-irs/data/dev/keycloak/oauth2#jwkSetUri>

aasProxy:
  submodel:
    username: <path:traceability-irs/data/dev/aasProxy/submodel#username>
    password: <path:traceability-irs/data/dev/aasProxy/submodel#password>
