apiVersion: v1
kind: Service
metadata:
  name: {{ include "aasproxy.fullname" . }}
  labels:
    {{- include "aasproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "aasproxy.selectorLabels" . | nindent 4 }}
