username: <path:traceability-irs/data/int/grafana#username>
password: <path:traceability-irs/data/int/grafana#password>

ingress:
  hosts:
    - host: "irs-grafana.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "irs-grafana.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret

oauthClientId: <path:traceability-irs/data/int/grafana#oauthClientId>
oauthClientSecret: <path:traceability-irs/data/int/grafana#oauthClientSecret>

configEnvs:
  - name: GF_SERVER_ROOT_URL
    value: 'https://irs-grafana.int.demo.catena-x.net'
  - name: GF_AUTH_GITHUB_ENABLED
    value: 'true'
  - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
    value: 'true'
  - name: GF_AUTH_GITHUB_TEAM_IDS
    value: '5783013'
  - name: GF_AUTH_GITHUB_SCOPES
    value: 'user:email,read:org'
  - name: GF_AUTH_GITHUB_AUTH_URL
    value: 'https://github.com/login/oauth/authorize'
  - name: GF_AUTH_GITHUB_TOKEN_URL
    value: 'https://github.com/login/oauth/access_token'
  - name: GF_AUTH_GITHUB_API_URL
    value: 'https://api.github.com/user'