server:
  port: 8080

spring:
  application:
    name: item-relationship-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: ${KEYCLOAK_OAUTH2_CLIENT_ID}
            client-secret: ${KEYCLOAK_OAUTH2_CLIENT_SECRET}
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI}
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_OAUTH2_JWK_SET_URI:https://default}

management:
  endpoints:
    web:
      exposure:
        include: health, threaddump, loggers, prometheus, info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, diskSpace
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http: true
    tags:
      application: ${spring.application.name}
  server:
    port: 4004

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    net.catenax.irs: INFO

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui
  writer-with-order-by-keys: true

irs:
  apiUrl: http://irs.int.demo.catena-x.net
  job:
    cleanup:
      scheduler:
        #          ┌───────────── second (0-59)
        #          │ ┌───────────── minute (0 - 59)
        #          │ │ ┌───────────── hour (0 - 23)
        #          │ │ │ ┌───────────── day of the month (1 - 31)
        #          │ │ │ │ ┌───────────── month (1 - 12) (or JAN-DEC)
        #          │ │ │ │ │ ┌───────────── day of the week (0 - 7)
        #          │ │ │ │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
        #          │ │ │ │ │ │
        completed: 0 0 * * * *
        failed: 0 0 * * * *
    jobstore:
      cron:
        expression: "*/20 * * * * ?"

blobstore:
  endpoint: "${MINIO_URL}"
  accessKey: "${MINIO_ACCESS_KEY}"
  secretKey: "${MINIO_SECRET_KEY}"
  bucketName: irsbucket

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      registry:
        baseConfig: default
      submodel:
        baseConfig: default

aasWrapper:
  host: "${AASWRAPPER_HOST:}"
  username: ${AASWRAPPER_USERNAME:}
  password: ${AASWRAPPER_PASSWORD:}

aspectTypes:
  default: SerialPartTypization

digitalTwinRegistry:
  url: https://semantics.int.demo.catena-x.net/registry

semanticsHub:
  url: https://semantics.int.demo.catena-x.net/hub/api/v1
  cleanup:
    #          ┌───────────── second (0-59)
    #          │ ┌───────────── minute (0 - 59)
    #          │ │ ┌───────────── hour (0 - 23)
    #          │ │ │  ┌───────────── day of the month (1 - 31)
    #          │ │ │  │ ┌───────────── month (1 - 12) (or JAN-DEC)
    #          │ │ │  │ │ ┌───────────── day of the week (0 - 7)
    #          │ │ │  │ │ │          (or MON-SUN -- 0 or 7 is Sunday)
    #          │ │ │  │ │ │
    scheduler: 0 0 23 * * *
  defaultUrns: >
    urn:bamm:io.catenax.serial_part_typization:1.0.0#SerialPartTypization
#    ,urn:bamm:com.catenax.assembly_part_relationship:1.0.0#AssemblyPartRelationship

