blobstore:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

irs:
  apiUrl: http://localhost:8080
  job:
    cleanup:
      scheduler:
        completed: 0 * * * * *
        failed: 0 * * * * *

spring:
  application:
    name: item-relationship-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: sa-cl6-cx-9
            client-secret: yeuF9syHZdgc247I517ydjYQw5fD8PJh
        provider:
          keycloak:
            token-uri: https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs