@startuml
skinparam monochrome true
skinparam shadowing false

 component [**IRS-Application**] <<System>> as IRS {
    component [**RecursiveJobHandler**] <<Component>> as RecursiveJobHandler
    component [**IrsController**] <<Component>> as IrsController
    component [**IrsItemGraphQueryService**] <<Component>> as IrsItemGraphQueryService
    component [**JobOrchestrator**] <<Component>> as JobOrchestrator
    component [**TransferProcessManager**] <<Subsystem>> as TransferProcessManager


    'component [**AASClient**] <<Subsystem>> as AASClient
    'component [**AASFacade**] <<Subsystem>> as AASFacade
    'component [**SubmodelClient**] <<Subsystem>> as SubmodelClient
    'component [**SubmodelFacade**] <<Subsystem>> as SubmodelFacade ' --> Level2 View

    () "BlobStore\nInterface" as StoreInterface
	port "IRS API" as API

    IrsController -left- IrsItemGraphQueryService

    IrsItemGraphQueryService -- JobOrchestrator
    IrsItemGraphQueryService - StoreInterface
    JobOrchestrator -right- StoreInterface
    JobOrchestrator -- TransferProcessManager
    JobOrchestrator -left- RecursiveJobHandler
    TransferProcessManager - StoreInterface

    IrsController - API
}
actor IrsApiConsumer

IrsApiConsumer -(0- API

component [**AASProxy**] <<System>> as AASProxy
TransferProcessManager .. AASProxy

database "BlobStore" as BlobStore
StoreInterface )-right- BlobStore

@enduml