@startuml 
skinparam monochrome true
skinparam shadowing false

interface "Catena-X \nNetwork" as X
component [**INT-Env**] <<Environment>> {
	component [**IRS**] <<System>> as IRS
	component [**AAS Wrapper**] <<System>> as AAS_W
	component [**AAS Proxy**] <<System>> as AAS_P
	component [**EDC Consumer**] <<System>> as EDC
}


actor IrsApiConsumer

IrsApiConsumer -right(0- IRS
IRS - AAS_P
AAS_P - AAS_W
AAS_W - EDC
EDC - X

@enduml