@startuml
skinparam monochrome true
skinparam shadowing false

interface BlobStoreInterface
component [**TransferProcessManager**] <<Subsystem>> as TransferProcessManager {
    component [**DigitalTwinRegistryFacade**] <<Component>> as DTRFacade {
        component [**DigitalTwinRegistryClient**] <<Component>> as DTRClient
    }
    component [**BlobPersistence**] <<Component>> as BlobPersistence
    component [**SubmodelFacade**] <<Component>> as SubmodelFacade {
        component [**SubmodelClient**] <<Component>> as SubmodelClient
    }
    component [**ExecutorService**] <<Component>> as ExecutorService
}

component [**AASProxy**] <<System>> as AASProxy
interface AASRegistryInterface
interface SubmodelInterface
AASRegistryInterface -- AASProxy
SubmodelInterface -- AASProxy
DTRClient --( AASRegistryInterface
SubmodelClient --( SubmodelInterface

database BlobStore
TransferProcessManager -- BlobStoreInterface
'BlobStoreInterface - TransferProcessManager
BlobStoreInterface )- BlobStore
@enduml