@startuml

skinparam monochrome true
skinparam shadowing false

node "Kuberneetes-Cluster / Argo CD" {

frame IRS-INT {
database "**MinIOBlobStore**" <<artifact>>
node "Java Runtime Environment" {
node "Java Spring Boot" {
artifact "**irs-XXX.jar**" <<artifact.executable>> as IRS
}
artifact "**edc.jar**" <<artifact.executable>>
artifact "**aas-wrapper.jar**" <<artifact.executable>> as AAS_W
artifact "**aas-proxy**" <<artifact.executable>> as AAS_P
}

}
}



@enduml