{
 "title": "IRS-API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Success Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{method=\"GET\", outcome=\"SUCCESS\"}"
    },
    {
     "expr": "http_server_requests_seconds_max{method=\"POST\", outcome=\"SUCCESS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RoundTrips",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_bucket{outcome=\"SUCCESS\", method=\"POST\"}"
    }
   ]
  },
  {
   "title": "Retry Request",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_retries_total{}" }
   ]
  },
  {
   "title": "Server Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_bucket{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RoundTrips",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{outcome=\"SUCCESS\", method=\"GET\"}[10y])))"
    }
   ]
  },
  {
   "title": "Number of Timeout",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_requests_timeouts_total{endpoint=\"registry\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Error Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{status=\"400\"}"
    }
   ]
  },
  {
   "title": "Successful Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{outcome=\"SUCCESS\"}"
    }
   ]
  },
  {
   "title": "Client Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "http_client_requests_seconds_max{}"
    },
    {
     "expr": "avg(http_client_requests_seconds_sum{client_name=\"irs-aas-registry.dev.demo.catena-x.net\"})"
    }
   ]
  }
 ]
}