apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "irs.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "irs.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_35=Secrets are handled by vault and need to be passed as environment variables
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "irs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "irs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # @url: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springprofile }}
            - name: MINIO_URL
              value: {{ .Values.minio.url }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "irs.secretName" . }}
                  key: minioUser
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "irs.secretName" . }}
                  key: minioPassword
            - name: KEYCLOAK_OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "irs.secretName" . }}
                  key: keycloakClientId
            - name: KEYCLOAK_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "irs.secretName" . }}
                  key: keycloakClientSecret
            - name: KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI
              value: {{ .Values.keycloak.oauth2.clientTokenUri }}
            - name: KEYCLOAK_OAUTH2_JWK_SET_URI
              value: {{ .Values.keycloak.oauth2.jwkSetUri }}
            - name: AASWRAPPER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "irs.secretName" . }}
                  key: aasWrapperUsername
            - name: AASWRAPPER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "irs.secretName" . }}
                  key: aasWrapperPassword
            - name: AASWRAPPER_HOST
              value: {{ .Values.aasWrapper.host }}
            - name: DIGITALTWINREGISTRY_URL
              value: {{ .Values.digitalTwinRegistry.url }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: actuator
              containerPort: 4004
              protocol: TCP
          # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: actuator
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: actuator
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}