name: "OWASP dependency scanner"

on:
  push:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    name: owasp-check
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: run maven owasp plugin
        run: mvn install -Pdependency-check

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: 'target/dependency-check-report.html'
